export const contactDefaults = {
  infoSectionLabel: 'CONTACT INFORMATION',
  infoHeading: 'Speak With the Right RUWASA Desk',
  infoDescription: 'Our administrative and technical teams receive public enquiries, community reports, partnership requests, and project-related correspondence.',
  phoneNumber: '0813 269 6321',
  phoneHelper: 'Monday to Friday, official working hours',
  emailAddress: 'info@ruwasa.gombe.gov.ng',
  emailHelper: 'Send enquiries, requests, and official correspondence',
  officeTitle: 'Gombe State RUWASA Headquarters',
  officeHelper: 'Gombe, Gombe State, Nigeria',
  workingHours: '8:00 AM - 4:00 PM',
  hoursHelper: 'Monday to Friday, excluding public holidays',
  communityReportNotice: 'For community water point reports, include the LGA, ward, community name, facility type, and a reachable phone number.',
  formSectionLabel: 'SEND A MESSAGE',
  formHeading: 'Submit an Enquiry to RUWASA',
  formDescription: 'Use the contact form to reach the Agency on rural water supply, sanitation, hygiene promotion, project updates, procurement, and partnership matters.',
  officialCorrespondenceTitle: 'Official Correspondence',
  officialCorrespondenceDescription: 'Submit letters, project enquiries, partnership requests, and administrative messages.',
  communitySupportTitle: 'Community Support',
  communitySupportDescription: 'Report rural water supply and sanitation issues for proper routing to the relevant desk.',
  responseHandlingTitle: 'Response Handling',
  responseHandlingDescription: 'The form layout captures the information needed for clear follow-up and record keeping.',
  guidanceSectionLabel: 'CONTACT GUIDANCE',
  guidanceHeading: 'Help Us Route Your Request Quickly',
  guidanceDescription: 'Clear details help RUWASA direct enquiries, community reports, and official requests to the appropriate administrative or technical desk.',
  prepareTitle: 'Prepare Your Enquiry',
  prepareDescription: 'Include your name, phone number, LGA, ward, community, and the specific water or sanitation matter that needs attention.',
  locationTitle: 'Share Location Details',
  locationDescription: 'For facility reports, mention the nearest landmark and whether the issue affects a borehole, hand pump, overhead tank, or sanitation facility.',
  officialRequestsTitle: 'Official Requests',
  officialRequestsDescription: 'For partnerships, procurement, media, or formal correspondence, provide a clear subject and organization details for proper routing.',
  addressSectionLabel: 'OFFICE ADDRESS',
  addressHeading: 'Visit the RUWASA Headquarters',
  addressDescription: 'The Agency receives official visitors, community representatives, contractors, development partners, and stakeholders through the appropriate administrative desks.',
  agencyName: 'Gombe State Rural Water Supply and Sanitation Agency',
  addressLocation: 'RUWASA Headquarters, Gombe, Gombe State',
  country: 'Nigeria',
  visitorNotice: 'Visitors are encouraged to call ahead for appointments, field reports, and document submissions.',
  mapEmbedUrl: '',
  facebookUrl: '',
  twitterUrl: '',
  instagramUrl: '',
  youtubeUrl: '',
};

export type ContactSettings = typeof contactDefaults;
export type ContactSettingKey = keyof ContactSettings;
export const contactSettingKeys = Object.keys(contactDefaults) as ContactSettingKey[];
